<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6010a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c64221c0a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "012809221d0a0a48656c6c6f5265706c79120f0a076d6573736167651801" .
            "2001280932490a0747726565746572123e0a0853617948656c6c6f12182e" .
            "68656c6c6f776f726c642e48656c6c6f526571756573741a162e68656c6c" .
            "6f776f726c642e48656c6c6f5265706c79220042360a1b696f2e67727063" .
            "2e6578616d706c65732e68656c6c6f776f726c64420f48656c6c6f576f72" .
            "6c6450726f746f5001a20203484c57620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

