<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actComment.proto

namespace Protocol\QD\ActCommentPbServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.QD.ActCommentPbServer.CreateRequest</code>
 */
class CreateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.CommonInParam inParam = 1;</code>
     */
    private $inParam = null;
    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.SimpleComment comment = 2;</code>
     */
    private $comment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\QD\ActCommentPbServer\CommonInParam $inParam
     *     @type \Protocol\QD\ActCommentPbServer\SimpleComment $comment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ActComment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.CommonInParam inParam = 1;</code>
     * @return \Protocol\QD\ActCommentPbServer\CommonInParam
     */
    public function getInParam()
    {
        return $this->inParam;
    }

    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.CommonInParam inParam = 1;</code>
     * @param \Protocol\QD\ActCommentPbServer\CommonInParam $var
     * @return $this
     */
    public function setInParam($var)
    {
        GPBUtil::checkMessage($var, \Protocol\QD\ActCommentPbServer\CommonInParam::class);
        $this->inParam = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.SimpleComment comment = 2;</code>
     * @return \Protocol\QD\ActCommentPbServer\SimpleComment
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.SimpleComment comment = 2;</code>
     * @param \Protocol\QD\ActCommentPbServer\SimpleComment $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkMessage($var, \Protocol\QD\ActCommentPbServer\SimpleComment::class);
        $this->comment = $var;

        return $this;
    }

}

