<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actComment.proto

namespace Protocol\QD\ActCommentPbServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.QD.ActCommentPbServer.GetResponse</code>
 */
class GetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.CommonOutParam outParam = 1;</code>
     */
    private $outParam = null;
    /**
     * Generated from protobuf field <code>repeated .protocol.QD.ActCommentPbServer.SimpleComment list = 2;</code>
     */
    private $list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\QD\ActCommentPbServer\CommonOutParam $outParam
     *     @type \Protocol\QD\ActCommentPbServer\SimpleComment[]|\Google\Protobuf\Internal\RepeatedField $list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ActComment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.CommonOutParam outParam = 1;</code>
     * @return \Protocol\QD\ActCommentPbServer\CommonOutParam
     */
    public function getOutParam()
    {
        return $this->outParam;
    }

    /**
     * Generated from protobuf field <code>.protocol.QD.ActCommentPbServer.CommonOutParam outParam = 1;</code>
     * @param \Protocol\QD\ActCommentPbServer\CommonOutParam $var
     * @return $this
     */
    public function setOutParam($var)
    {
        GPBUtil::checkMessage($var, \Protocol\QD\ActCommentPbServer\CommonOutParam::class);
        $this->outParam = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.QD.ActCommentPbServer.SimpleComment list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.QD.ActCommentPbServer.SimpleComment list = 2;</code>
     * @param \Protocol\QD\ActCommentPbServer\SimpleComment[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\QD\ActCommentPbServer\SimpleComment::class);
        $this->list = $arr;

        return $this;
    }

}

