<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actComment.proto

namespace Protocol\QD\ActCommentPbServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *输入参数通用结构体
 *
 * Generated from protobuf message <code>protocol.QD.ActCommentPbServer.CommonInParam</code>
 */
class CommonInParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 appId = 1;</code>
     */
    private $appId = 0;
    /**
     * Generated from protobuf field <code>int32 areaId = 2;</code>
     */
    private $areaId = 0;
    /**
     *用户信息
     *
     * Generated from protobuf field <code>int64 userId = 3;</code>
     */
    private $userId = 0;
    /**
     *来源名称
     *
     * Generated from protobuf field <code>string userIp = 4;</code>
     */
    private $userIp = '';
    /**
     *调用方服务器ip
     *
     * Generated from protobuf field <code>string serverIp = 5;</code>
     */
    private $serverIp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $appId
     *     @type int $areaId
     *     @type int|string $userId
     *          用户信息
     *     @type string $userIp
     *          来源名称
     *     @type string $serverIp
     *          调用方服务器ip
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ActComment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 appId = 1;</code>
     * @return int
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     * Generated from protobuf field <code>int32 appId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkInt32($var);
        $this->appId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 areaId = 2;</code>
     * @return int
     */
    public function getAreaId()
    {
        return $this->areaId;
    }

    /**
     * Generated from protobuf field <code>int32 areaId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAreaId($var)
    {
        GPBUtil::checkInt32($var);
        $this->areaId = $var;

        return $this;
    }

    /**
     *用户信息
     *
     * Generated from protobuf field <code>int64 userId = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     *用户信息
     *
     * Generated from protobuf field <code>int64 userId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->userId = $var;

        return $this;
    }

    /**
     *来源名称
     *
     * Generated from protobuf field <code>string userIp = 4;</code>
     * @return string
     */
    public function getUserIp()
    {
        return $this->userIp;
    }

    /**
     *来源名称
     *
     * Generated from protobuf field <code>string userIp = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUserIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->userIp = $var;

        return $this;
    }

    /**
     *调用方服务器ip
     *
     * Generated from protobuf field <code>string serverIp = 5;</code>
     * @return string
     */
    public function getServerIp()
    {
        return $this->serverIp;
    }

    /**
     *调用方服务器ip
     *
     * Generated from protobuf field <code>string serverIp = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServerIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->serverIp = $var;

        return $this;
    }

}

