<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actComment.proto

namespace Protocol\QD\ActCommentPbServer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.QD.ActCommentPbServer.QueryParam</code>
 */
class QueryParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 activityId = 1;</code>
     */
    private $activityId = 0;
    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    private $page = 0;
    /**
     * Generated from protobuf field <code>int32 size = 3;</code>
     */
    private $size = 0;
    /**
     * Generated from protobuf field <code>int32 orderType = 4;</code>
     */
    private $orderType = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $activityId
     *     @type int $page
     *     @type int $size
     *     @type int $orderType
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ActComment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 activityId = 1;</code>
     * @return int|string
     */
    public function getActivityId()
    {
        return $this->activityId;
    }

    /**
     * Generated from protobuf field <code>int64 activityId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setActivityId($var)
    {
        GPBUtil::checkInt64($var);
        $this->activityId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 size = 3;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>int32 size = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 orderType = 4;</code>
     * @return int
     */
    public function getOrderType()
    {
        return $this->orderType;
    }

    /**
     * Generated from protobuf field <code>int32 orderType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkInt32($var);
        $this->orderType = $var;

        return $this;
    }

}

